import {
  HiOutlineViewGrid,
  HiOutlineAcademicCap,
  HiOutlineUserGroup,
  HiOutlineDocumentText,
  
  HiOutlineCreditCard,
  HiOutlineCurrencyRupee,
  HiOutlineTag,
  HiOutlineBriefcase,
  HiOutlineBell,
  HiOutlineSupport,
  HiOutlineCog,
  HiOutlineCheckCircle,
  HiOutlineXCircle,
  HiOutlineTrendingUp,
  HiOutlineDeviceMobile,
  HiOutlineCollection,
  HiOutlineBookOpen,
  HiOutlineLightBulb,
  HiOutlineDocument,
  HiOutlineFilm,
  HiOutlineClipboardList,
} from 'react-icons/hi';

const iconMap = {
  dashboard: HiOutlineViewGrid,
  students: HiOutlineAcademicCap,
  parents: HiOutlineUserGroup,
  partners: HiOutlineBriefcase,
  content: HiOutlineDocumentText,
  subscriptions: HiOutlineCreditCard,
  commissions: HiOutlineCurrencyRupee,
  coupons: HiOutlineTag,
  notifications: HiOutlineBell,
  support: HiOutlineSupport,
  settings: HiOutlineCog,
  success: HiOutlineCheckCircle,
  error: HiOutlineXCircle,
  trendingUp: HiOutlineTrendingUp,
  mobile: HiOutlineDeviceMobile,
  collection: HiOutlineCollection,
  ebook: HiOutlineBookOpen,
  mindmap: HiOutlineLightBulb,
  pyq: HiOutlineClipboardList,
  film: HiOutlineFilm,
  document: HiOutlineDocument,
  'book-open': HiOutlineBookOpen,
  'light-bulb': HiOutlineLightBulb,
  'clipboard-list': HiOutlineClipboardList,

};

export const getIcon = (name) => iconMap[name] || HiOutlineViewGrid;
