import {
  HiOutlineViewGrid,
  HiOutlineAcademicCap,
  HiOutlineUserGroup,
  HiOutlineDocumentText,
  HiOutlineFilm,
  HiOutlineDocument,
  HiOutlineChartBar,
  HiOutlineCreditCard,
  HiOutlineCurrencyRupee,
  HiOutlineTag,
  HiOutlineBriefcase,
  HiOutlineDownload,
  HiOutlineBell,
  HiOutlineSupport,
  HiOutlineCog,
  HiOutlineCheckCircle,
  HiOutlineXCircle,
  HiOutlineTrendingUp,
  HiOutlineDeviceMobile,
  HiOutlineCollection,
  HiOutlineBookOpen,
  HiOutlineLightBulb,
  HiOutlineClipboardList,
} from 'react-icons/hi';

const iconMap = {
  dashboard: HiOutlineViewGrid,
  students: HiOutlineAcademicCap,
  parents: HiOutlineUserGroup,
  partners: HiOutlineBriefcase,
  content: HiOutlineDocumentText,
  subscriptions: HiOutlineCreditCard,
  commissions: HiOutlineCurrencyRupee,
  coupons: HiOutlineTag,
  notifications: HiOutlineBell,
  support: HiOutlineSupport,
  settings: HiOutlineCog,
  HiOutlineViewGrid,
  HiOutlineAcademicCap,
  HiOutlineUserGroup,
  HiOutlineDocumentText,
  HiOutlineFilm,
  HiOutlineDocument,
  HiOutlineChartBar,
  HiOutlineCreditCard,
  HiOutlineCurrencyRupee,
  HiOutlineTag,
  HiOutlineBriefcase,
  HiOutlineDownload,
  HiOutlineBell,
  HiOutlineSupport,
  HiOutlineCog,
  HiOutlineCheckCircle,
  HiOutlineXCircle,
  HiOutlineTrendingUp,
  HiOutlineDeviceMobile,
  HiOutlineCollection,
  HiOutlineBookOpen,
  HiOutlineLightBulb,
  HiOutlineClipboardList,
};

export const getIcon = (name) => iconMap[name] || HiOutlineViewGrid;
